version: "3.9"
services:
  project:
    image: redmine:5.0.5-alpine
    restart: always
    ports:
      - ${PORT}:3000
    environment:
      REDMINE_DB_ADAPTER: sqlite3
      REDMINE_DB_DATABASE: /usr/src/redmine/files/sqlite/redmine.db
      TZ: America/Bogota
    volumes:
      - ./data/files:/usr/src/redmine/files
      - ./data/themes/PurpleMine2:/usr/src/redmine/public/themes/PurpleMine2
#admin/admin
